services:
  redis:
    image: redis:7-alpine
    command: ["redis-server","--save","60","1","--loglevel","warning"]
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile.bot
    env_file: .env
    depends_on: [redis]
    restart: unless-stopped
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8080/health"]
      interval: 10s
      timeout: 2s
      retries: 5

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    env_file: .env
    depends_on: [redis]
    restart: unless-stopped
    volumes:
      - data:/data
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4g

volumes:
  data:
